import { Geist, Geist_Mono } from "next/font/google";
import Head from "next/head";
import "./globals.css";
import TopNav from "./components/TopNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

<Head>
  <link
    href="https://fonts.googleapis.com/css2?family=Poppins:wght@600&display=swap"
    rel="stylesheet"
  />
</Head>;

export const metadata = {
  title: "Lulu Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TopNav />
        {children}
      </body>
    </html>
  );
}
