'use client'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import TopNav from "./components/TopNav";
import { ThemeProvider, useTheme } from "./Context/ThemeContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// export const metadata = {
//   title: "Lulu Portfolio",
//   description: "Generated by create next app",
// };

// Move Theme Handling to a Separate Component
function ThemeWrapper({ children }) {
  const { theme } = useTheme(); // Get theme context

  return (
    <html lang="en" className={theme}> 
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <TopNav />
        {children}
      </body>
    </html>
  );
}

export default function RootLayout({ children }) {
  return (
    <ThemeProvider>
      <ThemeWrapper>{children}</ThemeWrapper>
    </ThemeProvider>
  );
}
